// Importe a fonte Inter diretamente do CSS do Google Fonts ou usando um pacote npm
import "../styles/globals.css"; // Importe os estilos globais

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Inclua aqui as importações de fontes ou outros metadados */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Outros metadados... */}
      </head>
      <body>{children}</body>
    </html>
  );
}
